name: Pull Request Check

on:
    pull_request:
        branches:
            - main

jobs:
    pull_request_check:
        name: Pull Request Check
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup PNPM
              uses: pnpm/action-setup@v3
              with:
                  run_install: true

            - name: Lint
              run: pnpm lint

            - name: Jest
              uses: ArtiomTr/jest-coverage-report-action@v2
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}

            - name: Build
              run: pnpm build
